imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
#        storage_id: session.storage.mock_file
# liip functional test bundle requires this:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
  # application/config/config_test.yml

liip_functional_test: ~

# liip functional test bundle requires this if fixture caching is used
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
