<?php

namespace Phprogress\FormDemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemoClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemoClassRepository extends EntityRepository
{
}
